name: root_checker
description: Plugin used for detecting root device in android and ios.
version: 0.1.4
author: Ricky Azhari <Ricky.azhari.pratama@gmail.com, kh4ri3@gmail.com>
homepage: https://github.com/rickyazhari/root_checker

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    package: com.neki.rootchecker
    pluginClass: RootCheckerPlugin
